@startuml
skinparam Linetype othro
package "Приложение для администратора" {

    frame "Экраны" {
        [Авторизация]
        [CRUD действия]
        [Формирование отчетов]
        [Фильтрация и сортировка данных]
        [Поиск данных]
        [Резервное копирование базы данных]
        [Статистика и графики]
        [Подтверждение регистрации]
    }

    frame "Управление состоянием" {
        [Хранилище данных]
    }

    [Авторизация] --> [Хранилище данных] : Вход
    [CRUD действия] --> [Хранилище данных] : Изменение данных
    [Формирование отчетов] --> [Хранилище данных] : Получение данных
    [Фильтрация и сортировка данных] --> [Хранилище данных] : Фильтрация и сортировка
    [Поиск данных] --> [Хранилище данных] : Поиск
    [Резервное копирование базы данных] --> [Хранилище данных] : Создание резервной копии
    [Статистика и графики] --> [Хранилище данных] : Получение данных
    [Подтверждение регистрации] --> [Хранилище данных] : Подтверждение

}

@enduml
