@startuml
skinparam Linetype curvy
!define SCREEN_CLASS bgColor Wheat
!define SCREEN_INTERFACE_CLASS bgColor LightBlue

package "Мобильное приложение для клиента" {

    frame "Экраны" {
        [Вход]
        [Регистрация]
        [Главная страница]
        [Поиск]
        [Детали задачи]
        [Мои задачи]
        [Профиль]
        }
    }

    frame "Компоненты" {
        [Кнопка]
        [Поле ввода]
        [Список]
        [Карточка задачи]
    }

    frame "Управление состоянием" {
        [Хранилище состояния]
    }

    [Вход] ..> [Главная страница] : Успешная аутентификация
    [Регистрация] ..> [Главная страница] : Успешная регистрация
    [Главная страница] ---> [Поиск] : Переход к поиску
    [Главная страница] --> [Мои задачи] : Переход к моим задачам
    [Главная страница] --> [Профиль] : Переход к профилю
    [Поиск] --> [Детали задачи] : Переход к деталям задачи
    [Мои задачи] --> [Детали задачи] : Переход к деталям задачи

    [Главная страница] --> "Управление состоянием" : Получение данных
    [Поиск] --> "Управление состоянием" : Получение данных
    [Мои задачи] --> "Управление состоянием" : Получение данных
    [Профиль] --> "Управление состоянием" : Получение данных

    [Кнопка] ...> [Главная страница] : Нажатие
    [Поле ввода] ..> [Главная страница] : Ввод текста
    [Список] ...> [Главная страница] : Переход к элементу списка
    [Карточка задачи] ...> [Главная страница] : Переход к задаче

}

@enduml
