
'skinparam Linetype curvy
'!define SCREEN_CLASS bgColor Wheat
'!define SCREEN_INTERFACE_CLASS bgColor LightBlue
'
'package "Мобильное приложение для клиента" {
'
'    frame "Экраны" {
'        [Авторизация]
'        [Выгрузка данных]
'        [Карточка товара]
'        [Корзина]
'        [Поиск]
'        [Фильтрация и сортировка данных]
'    }
'
'    frame "Управление состоянием" {
'        [Хранилище данных]
'    }
'
'    [Авторизация] --> [Хранилище данных] : Вход
'    [Выгрузка данных] --> [Хранилище данных] : Получение данных
'    [Корзина] --> [Хранилище данных] : Добавление товара
'    [Корзина] --> [Хранилище данных] : Удаление товара
'    [Поиск] --> [Хранилище данных] : Поиск товаров
'    [Фильтрация и сортировка данных] --> [Хранилище данных] : Фильтрация и сортировка
'
'}
''
''package "Мобильное приложение для клиента" {
''
''    frame "Компоненты" {
''class TaskCard {
'    - taskName: String
'    - status: String
'    - priority: String
'    - startDate: Date
'    - dueDate: Date
'    - description: String
'    - assignedTo: String
'    - progress: int
'    + displayTaskInfo(): void
'}
''    }
''
''}
'
@startuml


package "Мобильное приложение для клиента" {

    frame "Экраны" {
        [Авторизация]
        [Выгрузка данных]
        [Карточка товара]
        [Корзина]
        [Поиск]
        [Фильтрация и сортировка данных]
    }

    frame "Управление состоянием" {
        [Хранилище данных]
    }

    [Авторизация] --> [Хранилище данных] : Вход
    [Выгрузка данных] --> [Хранилище данных] : Получение данных
    [Корзина] --> [Хранилище данных] : Добавление товара
    [Корзина] --> [Хранилище данных] : Удаление товара
    [Поиск] --> [Хранилище данных] : Поиск товаров
    [Фильтрация и сортировка данных] --> [Хранилище данных] : Фильтрация и сортировка

}

'
'start
'partition "Уровень доступа 5" {
'    :Регистрация (с token и солью);
'    :Авторизация (с token и солью);
'    :CRUD действия над всеми таблицами;
'    :В запросах get сделать пагинацию данных;
'    :Множественное логическое удаление и восстановление данных;
'    :Фильтрация и сортировка данных;
'    :Поиск данных с пагинацией;
'    :Распределение запросов по ролям;
'}
'
'stop

@enduml
