@startuml
'skinparam linetype ortho

start
:Получение запроса;
if (Запрос на авторизацию?) then (Да)
  :Авторизация;
  if (Авторизация успешна?) then (Да)
    :Отправить токен;
  else (Нет)
    :Отправить ошибку авторизации;
  endif
elseif (Запрос на CRUD действие?) then (Да)
  :Обработка CRUD действия;
  if (Действие успешно выполнено?) then (Да)
    :Отправить ответ с данными;
  else (Нет)
    :Отправить сообщение об ошибке;
  endif
elseif (Запрос на фильтрацию/сортировку/поиск?) then (Да)
  :Обработка запроса на фильтрацию/сортировку/поиск;
  if (Обработка успешна?) then (Да)
    :Отправить отфильтрованные/отсортированные/найденные данные;
  else (Нет)
    :Отправить сообщение об ошибке;
  endif
elseif (Запрос на резервное копирование?) then (Да)
  :Выполнение резервного копирования базы данных;
  if (Резервное копирование успешно?) then (Да)
    :Отправить подтверждение;
  else (Нет)
    :Отправить сообщение об ошибке;
  endif
elseif (Запрос на формирование отчета?) then (Да)
  :Генерация отчета;
  if (Отчет сформирован успешно?) then (Да)
    :Отправить отчет в требуемом формате;
  else (Нет)
    :Отправить сообщение об ошибке;
  endif
elseif (Запрос на статистику и графики?) then (Да)
  :Формирование статистики и графиков;
  if (Статистика и графики сформированы успешно?) then (Да)
    :Отправить данные статистики и графики;
  else (Нет)
    :Отправить сообщение об ошибке;
  endif
else (Нет)
  :Отправить сообщение об ошибке;
endif
stop
@enduml
