@startuml
caption Agile-доска
class Пользователи {
    имя пользователя
    электронная почта
    пароль
}

class Проекты {
    название проекта
    описание
    дата начала
    дата окончания
}

class Команды {
    название команды
    руководитель
}



class Задачи {
    название задачи
    описание
    статус
    приоритет
    дата начала
    крайний срок
}

class "Комментарии к задачам" {
    текст комментария
    дата комментария
}

class "История изменений" {
    измененное поле
    старое значение
    новое значение
    дата изменения
}

class Логи {
    действие
    временная метка
}

class Роли {
    название роли
}

class Приоритеты {
    название приоритета
}

class "Статусы задач" {
    название статуса
}

Пользователи }|-l-|{ Команды
Пользователи --|{ "Комментарии к задачам"
Пользователи --|{ "История изменений"
"История изменений" }|-- Задачи
Пользователи -u-|{ Логи
Проекты --|{ Задачи
Приоритеты --|{ Задачи
Задачи }|-- "Статусы задач"
Пользователи }|-r-|{ Роли

@enduml
