# Generated by Django 4.2.6 on 2024-05-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
