# Generated by Django 4.2.6 on 2024-05-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker_api', '0002_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
