# Generated by Django 4.2.6 on 2024-05-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker_api', '0005_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='task_tracker_api.UserRole', to='task_tracker_api.role'),
        ),
    ]
