# Generated by Django 4.2.6 on 2024-05-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker_api', '0008_logicuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logicuser',
            name='token',
            field=models.CharField(default='', editable=False, max_length=255, verbose_name='Токен'),
        ),
    ]
