# Generated by Django 4.2.6 on 2024-05-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker_api', '0009_alter_logicuser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='lead',
        ),
        migrations.AddField(
            model_name='team',
            name='lead',
            field=models.ManyToManyField(to='task_tracker_api.user', verbose_name='Руководитель'),
        ),
    ]
