# Generated by Django 4.2.6 on 2024-05-08 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker_api', '0013_alter_team_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='lead',
        ),
        migrations.AddField(
            model_name='team',
            name='lead',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task_tracker_api.logicuser', verbose_name='Руководитель'),
        ),
    ]
