# Generated by Django 4.2.6 on 2024-05-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker_api', '0020_alter_employee_team_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='change_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_tracker_api.logicuser', verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
