name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Переход в директорию с .yml файлом
      run: cd ../../
    - name: Build the Docker image
      run: docker-compose up -d
 
